### ISSUE TITLE
OnDone Issue

### ISSUE THREAD

**Issue by ennihimbeqa** [matfire/bluetooth_classic#2]
OnDone doesn't get triggered, and if i make this method as a stream, it doesn't get canceled

return "Stream has been already set"
![Screenshot_2023-08-21_at_12 56 30](https://github.com/matfire/bluetooth_classic/assets/110820254/67b3b806-8a46-4d2c-bca4-b937ab9ee328)

**Comment by matfire** [comment]
Hi there,
the stream is never done, when you call the `stopScan` method there are no more elements being scanned and therefore pushed into the stream

**Comment by ennihimbeqa** [comment]
How can i send a data to bluetooth device? 
Example: 55 AA 00 02 23 00 30 19

**Comment by matfire** [comment]
- call `initPermissions` to check if you have the right permissions to use this plugin
- if you are already paired to the device, find it with `getPairedDevices`
- if not, you can call `startScan` to start scanning (I know, who'd have guessed, right ?) and listen to the `onDeviceDiscovered` to get the devices as they come in
- when done with scanning, you can call `stopScan`
- connect to the device using the `connect` function providing the device mac address and the UUID of the service you want to connect to (serial, for example)
- you can check the connection status on the `onDeviceStatusChange` stream
- once connected, you can use the `write` function passing in the message you want to send
