### ISSUE TITLE
iOS iPhone13 error “ Unhandled Exception: MissingPluginException”

### ISSUE THREAD

**Issue by liyinchigithub** [matfire/bluetooth_classic#7]
iOS iPhone13 error

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method startDiscovery on channel com.matteogassend/bluetooth_classic

**Comment by ZvonimirBabic** [comment]
IOS does not support Bluetooth Classic unless the device is MFI certified.

**Comment by liyinchigithub** [comment]
thank you
